i. Reproducir la matriz B:

[[0.4 0.41 0.42 0.43 0.44]

[0.45 0.46 0.47 0.48 0.49]

[0.5 0.51 0.52 0.53 0.54]

[0.55 0.56 0.57 0.58 0.59]

[0.6 0.61 0.62 0.63 0.64]

[0.65 0.66 0.67 0.68 0.69]

[0.7 0.71 0.72 0.73 0.74]

[0.75 0.76 0.77 0.78 0.79]]

ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas.

iii. Agregar una linea al final con el promedio de cada columna

iv. Agregar una columna al final con el valor maximo de cada fila

v. Guardar en un archivo.

In [1]:
import numpy as np

In [7]:
#Creamos primero el vector de todos los numeros
B_vector = np.arange(0.4, 0.8, 0.01)
B_vector

array([0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ,
       0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61,
       0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72,
       0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79])

In [9]:
#Convertimos el vector en una matriz
B =B_vector.reshape(8,5)
B

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])