In [1]:
import numpy as np

Ejercicio 1:
Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por filas (1,2,3,4...).


Ejercicio 2:
i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por columnas.

ii. reemplazar los elementos que tengan al menos un 3 por -99.

In [84]:
#Creando primero el arreglo de 1-64
linea = np.arange(1,65,1)
linea

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [85]:
#Organizando los valores en una matriz de 8x8 por filas
filas = linea.reshape(8,8)
filas

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [86]:
#Transponiendo los valores a una matriz de 8x8 por columnas
columns = filas.transpose()
columns

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [105]:
#Cambiando los valores que tengan 3 por un -99
for indrow, row in enumerate (columns): #se corre por fila y se obtiene los indices
    for indcol, element in enumerate (row): #se corre por columnas y se obtiene los indices
        x = str(element) #convertimos a string el indice
        temp = x.find('3') #se encuentra los elementos con el elemento '3'
        if (temp != -1): #se busca los elementos con el -1
            #print(element, indcol, indrow)
            columns[indrow, indcol] = -99 #pasamos los indices para cambiar el valor a -99
columns

array([[  1,   9, -99,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26, -99,  42,  50,  58],
       [-99,  11,  19,  27, -99, -99, -99,  59],
       [  4,  12,  20,  28, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99,  61],
       [  6,  14, -99, -99, -99,  46,  54,  62],
       [  7,  15, -99, -99, -99,  47,  55, -99],
       [  8,  16,  24, -99,  40,  48, -99,  64]])

In [79]:
#Método de Sergio
for i in range(8):
    for j in range(8):
        #print(columns[i][j])
        x = str(columns[i][j])
        temp = x.find('3')
        if(temp != -1):
            columns[i][j]=-99

In [80]:
print(columns)

[[  1   9 -99  25 -99  41  49  57]
 [  2  10  18  26 -99  42  50  58]
 [-99  11  19  27 -99 -99 -99  59]
 [  4  12  20  28 -99 -99 -99 -99]
 [-99 -99 -99 -99 -99 -99 -99  61]
 [  6  14 -99 -99 -99  46  54  62]
 [  7  15 -99 -99 -99  47  55 -99]
 [  8  16  24 -99  40  48 -99  64]]
